app:
  name: miportfolio
  image:
    repository: morgadoberruezo/miportfolio
    tag: 56a930eaa92b2e1c66fb8a93ec8ff33ccd705f74
    pullPolicy: Always
  # containerPort: 3000   
  container: 
    name: miportfolio
    port: 80
    replicas: 1
  service:
    type: ClusterIP
    port: 3000
    targetPort: 30087
  ingress:
    enabled: true
    className: nginx
    host: miportfolio.jamorgado.es
    path: /
    tls:
      enabled: true
      secretName: miportfolio-tls
    certManager:
      enabled: true
      clusterIssuer: letsencrypt-prod

# postgres:
#   name: usuarios-postgres
#   image:
#     repository: postgres
#     tag: 56a930eaa92b2e1c66fb8a93ec8ff33ccd705f74
#     pullPolicy: IfNotPresent
#   service:
#     port: 5432
#   auth:
#     database: bdusuarios
#     username: admin
#     password: admin
#   persistence:
#     enabled: true
#     size: 2Gi
#     storageClassName: "microk8s-hostpath"   # pon aqu√≠ tu storageClass si quieres fijarla
