apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-miportfolio
  namespace: namespace-miportfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miportfolio
  template:
    metadata:
      labels:
        app: miportfolio
    spec:
      volumes:
        - name: logs
          hostPath:
            path: /root/logs
            type: DirectoryOrCreate
      containers:
        - name: miportfolio
          image: morgadoberruezo/miportfolio:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: config-miportfolio
          ports:
            - containerPort: 80
          volumeMounts:
            - name: logs
              mountPath: /home/morgado/logs
          resources:
              requests:
                cpu: "100m"
                memory: "128Mi"
              limits:
                cpu: "500m"
                memory: "256Mi"
      
        # ðŸ”¹ Montaje del ConfigMap como fichero
          # volumeMounts:
          #   - name: webtaller-config-volume
          #     mountPath: /etc/webtaller
          #     readOnly: true
      # ðŸ”¹ DefiniciÃ³n del volumen desde el ConfigMap
      # volumes:
      #   - name: webtaller-config-volume
      #     configMap:
      #       name: webtaller-config