apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-miportfolio
  namespace: namespace-miportfolio
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: miportfolio.jamorgado.es
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service-miportfolio
                port:
                  number: 80
