apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: miportfolio
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/morgadodesarrollador/portfolioHelm.git
    targetRevision: main
    path: deploy/kubernetes/helm
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: miportfolio

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
