apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-{{ .Values.app.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.app.container.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      volumes:
        - name: logs
          hostPath:
            path: /root/logs
            type: DirectoryOrCreate
      containers:
        - name: {{ .Values.app.container.name }}
          image: {{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: config-{{ .Values.app.name }}
          ports:
            - containerPort: {{ .Values.app.container.port }}
          volumeMounts:
            - name: logs
              mountPath: /root/logs
          resources:
              requests:
                cpu: "100m"
                memory: "128Mi"
              limits:
                cpu: "500m"
                memory: "256Mi"
      
        # ðŸ”¹ Montaje del ConfigMap como fichero
          # volumeMounts:
          #   - name: webtaller-config-volume
          #     mountPath: /etc/webtaller
          #     readOnly: true
      # ðŸ”¹ DefiniciÃ³n del volumen desde el ConfigMap
      # volumes:
      #   - name: webtaller-config-volume
      #     configMap:
      #       name: webtaller-config