{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.container.name }}-config
  namespace: {{ .Release.Namespace }}
data:
  NATS_SERVERS: {{ .Values.global.nats.url| quote }}
  REPO_GIT: {{ .Values.global.env.REPO_GIT | quote }}
  PORT: {{ .Values.global.env.PORT | quote }}
  DATABASE_HOST: {{ .Values.env.DATABASE_HOST | quote }}
  DATABASE_PORT: {{ .Values.env.DATABASE_PORT | quote }}
  DATABASE_NAME: {{ .Values.env.DATABASE_NAME | quote }}
  DATABASE_USER: {{ .Values.env.DATABASE_USER | quote }}
{{- end }}
