
services:
  postgresBDusarios:
    image: postgres:15-alpine
    container_name: usuarios-postgres
    env_file:
      - .app.env
    environment:
      # POSTGRES_HOST: ContainerName || nameService (postgresUsarios)
      # POSTGRES_PORT: 5432
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    networks:
      - caronte-network
      
  ms-usuarios-nest:
    profiles: ["usuarios"]
    build:
      context: ${CONTEXTO}
      # dockerfile: ./apps/${MICROSERVICIO}/deploy/Dockerfile
      dockerfile: ./deploy/build_img/Dockerfile
      args:
        - CONTEXT=${CONTEXTO}
        - MICROSERVICIO=${MICROSERVICIO}
    image: morgadoberruezo/caronte-${MICROSERVICIO}
    container_name: caronte-ms-usuarios
    ports:
      - "${PORT}:3000"
    env_file: # variable dentro del contenedor en ejecucion
      - .app.env              # especifico del microservicio
      - ../../../deploy/.env  # general del monorepo
    environment:
      NODE_ENV: production
    volumes:
      - ./logs:/root/logs
    networks:
      - caronte-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('net').connect(3001)"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres_data:

networks:
  caronte-network:
    external:
      true